### ISSUE TITLE
File parameter updates

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/hydra-bot#1]
Rather than a separate 'files' parameter to addEntry, this should be taken from the 
files=['sdfsd'] component of the metadata.   This should either be a URL, as in file://// or http:///.
If it's not a valid url, it should be considered a filepath with a base as the location of the streaming json file.

**Comment by jrmerz** [comment]
This is taken from the files component of the metadata.  The sample json you sent me has a pointer to data that does not exist on my machine, thus test.js has you set it manually.
